[project]
name = "cloudphonebook-api"
version = "0.1.0"
description = "Backend API for CloudPhoneBook"
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn[standard]"
]

[tool.uvicorn]
factory = false
